[Distribution]
Distribution=debian
Release=trixie

[Output]
Format=disk
ImageId=onprem-host
ImageVersion=0.1.0

[Content]
Bootable=yes
Bootloader=systemd-boot-signed
Packages=
    systemd-boot
    systemd
    linux-image-amd64
    firmware-linux-free
    firmware-linux
    sudo
    openssh-server
    vim
    less
    ca-certificates
Hostname=onprem
Timezone=Europe/Athens
Locale=el_GR.utf8

[Validation]
Checksum=yes
SecureBoot=yes

[Build]
ToolsTree=default
Incremental=yes
