[Distribution]
Distribution=debian
Release=trixie
Repositories=contrib,non-free,non-free-firmware

[Output]
Format=disk
ImageId=onprem-host
ImageVersion=0.1.0

[Include]
Include=mkosi-vm

[Content]
Bootloader=systemd-boot-signed
Packages=
    apt
    ca-certificates
    e2fsprogs
    firmware-linux-free
    firmware-misc-nonfree
    man-db
    openssh-server
    parted
    sudo
    systemd-cryptsetup
    systemd-repart
    vim
Hostname=onprem
Timezone=Europe/Athens
Locale=el_GR.utf8

[Validation]
Checksum=yes
#SecureBoot=yes

[Build]
ToolsTree=default
Incremental=yes
